language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
- echo -e "Host http://39.97.40.43\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod +x ./publish.sh
- sudo apt-get update
install:
- npm install
- sudo apt-get install sshpass
script:
- hexo clean
- hexo g
after_success:
- export SSHPASS=$DEPLOY_PASS
- ./publish.sh
- sshpass -e scp -o stricthostkeychecking=no -r public root@39.97.40.43:/usr/local/nginx

env:
  global:
  - GH_REF: github.com/hyxkiller/hyxkiller.github.io.git
  - secure: "NyrHqoYrzJAtxJHHK3A5dljFJQAFoijB4nBFGamlhEC2nlC2oATC4AYPGmK3K/W0l/d0DWX0ilREX71GQ/eJkt09jxP4IhPFRQcCYMelHYOaK31+IGhNH0S2ZFAHWUoGdawAKnOrzAIrg+uyZdNQTX2vVIwOP8NVmE/jvrP/9k8AFKI+V6JzW3Mlb6/9xHQEA3RN/HIkEI1n1zU2xeXjFtg4ETw7OrZZo0jDxauyVN5YT+/+SvvNW+cTIMmmOHIeQwT+ThzVR+DX+BJ6BESIvnFjWe8LpMY6Bt1mcioC+onI+2W2iDk/SDNFR0y/McyLHFICyRqfXnHLRVzpAmlID3MKR6bLLa9xcere8WTUU31hVkVWRh1SbpyFFxKrCkYObyPE/sg3Na1BL+nv5znvDS31S4pjzMgj9+SCyajfDb9znIag1j0oYOu2hsXqwuJty5gdsjQoenzBBU+07GyzxFDKKJ6V5n10MCIqxVrJJd0vTPo7Xd2Afw5buhFe7dRnRzCS5dOz4rAxuaw//zzbAlHxLDkSLIuFHm4owYwZpGCUUtIkuAfc4lkVtVgbNe30wRkgINyEfpTc5IoODJN3ZzBAOvPDxVevr/hHrfv+4SPAfWC0Ix/t8ILOn4MXm8xPmNiWDP6FapJsp+K6d2r2Gsynk13yb0/+RHyRZ+dr1Z4="
  - secure: "SgYA8a1SwWxcP2Lwn3T0TwuToXwUvNuTjAKgjKYqJwEgrsJyKdcugeH57lwNFIYIOJK91njScvCZ4+Oym6ScsjmPopM13lYMZzcnxySR5s6VtGx3t7d4/AMG9gbEQnBGwaIqt8BMrHIMXnkzK0/xDYep513rOKx3K8FKAbXIiCQY8gpolpNug9dxTl6vgILEYwBijq5oW6ZDnl8UV4dPw6gtKkHK7JH2VsQZnb/RpArfBXKO6MxiODoMuAmJiv/mIoIVp2V9jXfr5uvr6osmwwOJ8ibVxvVPhg+lirHNmNqrSZtPVBxmI61cx8dNEZuvjGBwvj8YryXWXolRKIgXI+V80Rl8II2SIKHk4YtKtd6vuQbrAdl7yf3SleupLjKs3jAxU+AL83sBwSwcZuH0i0BCPsjNQ8euA8QJ0f4VBzGxPb7ILpLS8L1WQPylUjQyaMyotPSlFXwLQrl7KWV0j878xOsMtu7a3mMBkHOwgdMH4oncrUCMOg4DoncE1TdUi1peeQ/g44LRObmr0K0YYSdviplIPYisuiZxatAxa2v1+XpidIJjXdIs4h6g5g2B8S3TzHtIlrAqK8S1ccgmhpNXSe0ILLRzkxfpQpGim1C5h7aU+/dFIvY6RkAxx3jsQRF/CZzQaiQYIFCdO565VrIkgMisDkFd0UA0NAbtxKA="
