language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
# - openssl aes-256-cbc -K $encrypted_c8bcf74436a5_key -iv $encrypted_c8bcf74436a5_iv
#   -in id_rsa.enc -out id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - eval $(ssh-agent)
# - ssh-add ~/.ssh/id_rsa
- git config --global user.name 'hyxkiller'
- git config --global user.email '546495041@qq.com'
# - sed -i'' https://github.com/hyxkiller/hyxkiller.github.io.git~https://${GIT_REPO}@github.com/<yourname>/<reopname>.git~" _config.yml
# - git clone https://github.com/hyxkiller/hyxkiller.github.io.git
- npm install -g hexo-cli
install:
- npm i
script:
- hexo clean
- hexo generate 
- hexo deloy
after_success:
- cd ./public
- git init
- git add .
- git commit -m 'travis ci update'
- git push --quiet --force https://${GIT_REPO}@github.com/hyxkiller/hyxkiller.github.io.git master
