language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_c8bcf74436a5_key -iv $encrypted_c8bcf74436a5_iv
  -in id_rsa.enc -out id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - eval $(ssh-agent)
# - ssh-add ~/.ssh/id_rsa
- git config --global user.name 'hyxkiller'
- git config --global user.email '546495041@qq.com'
- npm install -g hexo-cli
install:
- npm i
script:
- hexo clean
- hexo generate
after_success:
- cd ./public
- git init
- git add .
- git commit -m 'travis ci update'
- git remote add origin https://9c589f6a742d61eb423b4d7ceb033ce0cbb6d55a@github.com/hyxkiller/hyxkiller.github.io.git
- git pull
- git push --quiet --force https://9c589f6a742d61eb423b4d7ceb033ce0cbb6d55a@github.com/hyxkiller/hyxkiller.github.io.git master
