language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_c8bcf74436a5_key -iv $encrypted_c8bcf74436a5_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- echo -e "Host http://39.97.40.43\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod +x ./publish.sh
install:
- npm install
script:
- hexo clean
- hexo g 
after_success:
  - ./publish.sh
env:
    global:
        # Github Pages
        - GH_REF: github.com/hyxkiller/hyxkiller.github.io.git