language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 39.97.40.43
before_deploy: 
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in travis_rsa.pub.enc -out travis_rsa.pub -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
before_install:
# - openssl aes-256-cbc -K $encrypted_c8bcf74436a5_key -iv $encrypted_c8bcf74436a5_iv
#   -in travis_rsa.pub.enc -out travis_rsa.pub -d
# - chmod 600 travis_rsa.pub
# - echo -e "Host http://39.97.40.43\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod +x ./publish.sh
install:
- npm install
script:
- hexo clean
- hexo g
after_success:
- ./publish.sh
env:
  global:
  - GH_REF: github.com/hyxkiller/hyxkiller.github.io.git
