language: node_js
node_js: stable
branches:
  only:
  - source
cache:
  directories:
  - node_modules
before_install:
# - openssl aes-256-cbc -K $encrypted_c8bcf74436a5_key -iv $encrypted_c8bcf74436a5_iv
#   -in id_rsa.enc -out id_rsa -d
# - chmod 600 ~/.ssh/id_rsa
# - eval $(ssh-agent)
# - ssh-add ~/.ssh/id_rsa
# - sed -i'' https://github.com/hyxkiller/hyxkiller.github.io.git~https://${GIT_REPO}@github.com/<yourname>/<reopname>.git~" _config.yml
# - git clone https://github.com/hyxkiller/hyxkiller.github.io.git
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod +x ./publish.sh
install:
- npm install
script:
- hexo clean
- hexo g 
after_success:
  - ./publish.sh
# - cd ./public
# - git init
# - git add .
# - git commit -m 'travis ci update'
# - git push --quiet --force https://${GIT_REPO}@github.com/hyxkiller/hyxkiller.github.io.git master
env:
    global:
        # Github Pages
        - GH_REF: github.com/hyxkiller/hyxkiller.github.io.git